import {useEffect,useState} from 'react';import {api} from '../../services/api';import {Page,ResourceState,useResource,useAction} from '../../components/ui/Resource';
interface Props{onShowToast:(title:string,note?:string)=>void}
export function HarnessConfigView({onShowToast}:Props){const config=useResource(api.getHarnessConfig);const servers=useResource(api.getMCPServers);const memories=useResource(api.getMemoryEntries);const skills=useResource(api.getCustomSkills);const traces=useResource(api.getAgentTraces);const action=useAction(onShowToast);const [enabled,setEnabled]=useState<string[]>([]);const [history,setHistory]=useState(10);const [name,setName]=useState('');const [endpoint,setEndpoint]=useState('');const [headers,setHeaders]=useState('');const [memoryTitle,setMemoryTitle]=useState('');const [memory,setMemory]=useState('');const [file,setFile]=useState<File|null>(null);
 useEffect(()=>{if(config.data){try{setEnabled(JSON.parse(config.data.enabled_skills))}catch{setEnabled([])}setHistory(config.data.max_history_turns)}},[config.data]);
 return <Page title="副驾驶执行配置" description="权限和工具清单以服务端配置为准。外部 MCP 工具需要审批；记忆候选需人工审核后才进入上下文。">
 <form className="card panel grid gap-3" onSubmit={e=>{e.preventDefault();void action.run(()=>api.updateHarnessConfig({enabled_skills:JSON.stringify(enabled),max_history_turns:history}),'执行配置已保存')}}><h2>允许的能力</h2><ResourceState resource={config}/>{[['monitor','监测与调度'],['diagnosis','诊断'],['content','内容生成'],['publish','对外发布'],['evolution','实验评估']].map(([id,label])=><label key={id}><input type="checkbox" checked={enabled.includes(id)} onChange={e=>setEnabled(current=>e.target.checked?[...current,id]:current.filter(v=>v!==id))}/>{label}</label>)}<label>上下文保留轮数<input type="number" min={1} max={40} value={history} onChange={e=>setHistory(Number(e.target.value))}/></label><p>当前按近期对话和已批准记忆构建上下文。模型在系统设置中配置。</p><button className="btn primary" disabled={action.busy||!config.data}>保存</button></form>
 <form className="card panel grid gap-3" onSubmit={e=>{e.preventDefault();void action.run(async()=>{await api.createMCPServer({name,endpoint_url:endpoint,transport_type:'streamable_http',auth_headers:headers,is_active:true});setHeaders('')},'MCP 服务已保存')}}><h2>外部 MCP 服务</h2><label>名称<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>HTTPS Streamable HTTP 地址<input type="url" required value={endpoint} onChange={e=>setEndpoint(e.target.value)}/></label><label>认证请求头 JSON<textarea placeholder='{"Authorization":"Bearer …"}' value={headers} onChange={e=>setHeaders(e.target.value)}/></label><button className="btn" disabled={action.busy}>添加服务</button></form>
 <ResourceState resource={servers} empty={!servers.data?.items.length}/>{servers.data?.items.map(s=><article className="card panel" key={s.id}><h3>{s.name}</h3><p>{s.endpoint_url} · {s.has_credentials?'已加密配置凭证':'无凭证'} · {s.is_active?'启用':'停用'}</p><button className="btn" disabled={action.busy} onClick={()=>void action.run(async()=>{const result=await api.pingMCPServer(s.id);if(result.status!=='online')throw new Error(result.error||'连接失败');onShowToast('连接成功',`${result.tools_count} 个真实工具`)},'协议握手已完成')}>测试协议连接</button><button className="btn" disabled={action.busy} onClick={()=>void action.run(()=>api.updateMCPServer(s.id,{is_active:!s.is_active}),'服务状态已保存')}>{s.is_active?'停用':'启用'}</button><button className="btn" disabled={action.busy} onClick={()=>void action.run(()=>api.deleteMCPServer(s.id),'服务已删除')}>删除</button></article>)}
 <form className="card panel grid gap-3" onSubmit={e=>{e.preventDefault();void action.run(()=>api.createMemoryEntry({memory_type:'user_pref',title:memoryTitle,content:memory}),'偏好候选已提交')}}><h2>长期记忆</h2><label>偏好标题<input required value={memoryTitle} onChange={e=>setMemoryTitle(e.target.value)}/></label><label>运营偏好<textarea required value={memory} onChange={e=>setMemory(e.target.value)}/></label><button className="btn" disabled={action.busy}>提交待审核偏好</button></form>
 <ResourceState resource={memories} empty={!memories.data?.items.length}/>{memories.data?.items.map(m=><article className="card panel" key={m.id}><h3>{m.title}</h3><p>{m.content}</p><p>{m.memory_type} · {m.status} · 来源：{m.evidence||m.extraction_source}</p>{m.status==='pending'&&m.memory_type!=='brand_truth'&&<button className="btn" disabled={action.busy} onClick={()=>void action.run(()=>api.approveMemory(m.id),'记忆已批准')}>核对并批准</button>}{m.memory_type==='brand_truth'&&<p>品牌声明请在可信事实页面补充来源并审核。</p>}<button className="btn" disabled={action.busy} onClick={()=>void action.run(()=>api.deleteMemoryEntry(m.id),'记忆已删除')}>删除</button></article>)}
 <form className="card panel grid gap-3" onSubmit={e=>{e.preventDefault();if(file)void action.run(()=>api.importCustomSkill(file),'技能已导入，审核后手动启用')}}><h2>自定义技能</h2><label>包含 SKILL.md 的 ZIP<input type="file" accept=".zip" required onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="btn" disabled={action.busy}>导入</button></form><ResourceState resource={skills} empty={!skills.data?.items.length}/>{skills.data?.items.map(s=><article className="card panel" key={s.id}><h3>{s.name}</h3><p>{s.description} · {s.is_active?'启用':'待审核/停用'}</p><details><summary>审查技能内容</summary><pre className="whitespace-pre-wrap">{s.content}</pre></details><button className="btn" disabled={action.busy} onClick={()=>void action.run(()=>api.toggleCustomSkill(s.id),s.is_active?'技能已停用':'技能已启用')}>{s.is_active?'停用':'审核并启用'}</button></article>)}
 <article className="card panel"><h2>执行追踪</h2><ResourceState resource={traces} empty={!traces.data?.items.length}/>{traces.data?.items.map(t=><details key={t.id}><summary>{t.status} · {t.user_prompt} · {t.total_duration_ms}ms</summary><pre className="whitespace-pre-wrap">{t.timeline_json}</pre></details>)}</article>
 </Page>}
