package middleware

import "github.com/robbinsz/bgeo/internal/repository"

type projectRoutePolicy struct {
	permission   string
	execution    bool
	ownedSession bool
	resource     func() interface{}
}

// Every project route has an explicit policy. Unregistered routes fail closed.
var projectPolicies = map[string]projectRoutePolicy{
	"GET /api/v1/system/status":                       {permission: "admin"},
	"GET /ws/live":                                    {"read", false, false, nil},
	"GET /api/v1/projects/current":                    {"read", false, false, nil},
	"PUT /api/v1/projects/current":                    {"admin", false, false, nil},
	"GET /api/v1/projects/facts":                      {"read", false, false, nil},
	"GET /api/v1/projects/competitors":                {"read", false, false, nil},
	"GET /api/v1/monitor/queries":                     {"read", false, false, nil},
	"POST /api/v1/monitor/queries":                    {"write", false, false, nil},
	"POST /api/v1/monitor/runs":                       {"write", true, false, nil},
	"GET /api/v1/monitor/snapshots":                   {"read", false, false, nil},
	"GET /api/v1/diagnosis/opportunities":             {"read", false, false, nil},
	"POST /api/v1/diagnosis/opportunities/:id/status": {"write", false, false, func() interface{} { return &repository.OpportunityModel{} }},
	"GET /api/v1/strategies":                          {"read", false, false, nil},
	"POST /api/v1/strategies":                         {"write", false, false, nil},
	"GET /api/v1/content/assets":                      {"read", false, false, nil},
	"POST /api/v1/content/assets":                     {"write", false, false, nil},
	"POST /api/v1/content/verify":                     {"write", false, false, nil},
	"GET /api/v1/evolution/rules":                     {"read", false, false, nil},
	"POST /api/v1/evolution/runs":                     {"write", true, false, nil},
	"POST /api/v1/evolution/rules/:id/approve":        {"review", false, false, func() interface{} { return &repository.RuleModel{} }},
	"POST /api/v1/evolution/rules/:id/rollback":       {"review", false, false, func() interface{} { return &repository.RuleModel{} }},
	"GET /api/v1/overview/metrics":                    {"read", false, false, nil},
	"POST /api/v1/copilot/chat":                       {"write", true, false, nil},
	"POST /api/v1/copilot/resume":                     {"write", true, false, nil},
	"GET /api/v1/copilot/sessions":                    {"read", false, false, nil},
	"GET /api/v1/copilot/sessions/:id":                {"read", false, true, func() interface{} { return &repository.CopilotSessionModel{} }},
	"DELETE /api/v1/copilot/sessions/:id":             {"write", false, true, func() interface{} { return &repository.CopilotSessionModel{} }},
	"PATCH /api/v1/copilot/sessions/:id":              {"write", false, true, func() interface{} { return &repository.CopilotSessionModel{} }},
	"GET /api/v1/copilot/audit-logs":                  {"read", false, false, nil},
	"GET /api/v1/copilot/traces":                      {"read", false, false, nil},
	"GET /api/v1/copilot/traces/:id":                  {"read", false, false, func() interface{} { return &repository.AgentExecutionTraceModel{} }},
	"GET /api/v1/harness/config":                      {"read", false, false, nil},
	"PUT /api/v1/harness/config":                      {"admin", false, false, nil},
	"GET /api/v1/harness/mcp-servers":                 {"read", false, false, nil},
	"POST /api/v1/harness/mcp-servers":                {"admin", false, false, nil},
	"PUT /api/v1/harness/mcp-servers/:id":             {"admin", false, false, func() interface{} { return &repository.MCPServerModel{} }},
	"DELETE /api/v1/harness/mcp-servers/:id":          {"admin", false, false, func() interface{} { return &repository.MCPServerModel{} }},
	"POST /api/v1/harness/mcp-servers/:id/ping":       {"admin", false, false, func() interface{} { return &repository.MCPServerModel{} }},
	"GET /api/v1/harness/memory":                      {"read", false, false, nil},
	"POST /api/v1/harness/memory":                     {"admin", false, false, nil},
	"PUT /api/v1/harness/memory/:id":                  {"admin", false, false, func() interface{} { return &repository.MemoryEntryModel{} }},
	"DELETE /api/v1/harness/memory/:id":               {"admin", false, false, func() interface{} { return &repository.MemoryEntryModel{} }},
	"POST /api/v1/harness/memory/trigger-hook":        {"admin", false, false, nil},
	"GET /api/v1/harness/skills":                      {"read", false, false, nil},
	"POST /api/v1/harness/skills":                     {"admin", false, false, nil},
	"POST /api/v1/harness/skills/import":              {"admin", false, false, nil},
	"PUT /api/v1/harness/skills/:id":                  {"admin", false, false, func() interface{} { return &repository.CustomSkillModel{} }},
	"DELETE /api/v1/harness/skills/:id":               {"admin", false, false, func() interface{} { return &repository.CustomSkillModel{} }},
	"PUT /api/v1/harness/skills/:id/toggle":           {"admin", false, false, func() interface{} { return &repository.CustomSkillModel{} }},
	"GET /api/v1/system/ai-config":                    {"read", false, false, nil},
	"PUT /api/v1/system/ai-config":                    {"admin", false, false, nil},
	"POST /api/v1/system/ai-config/test":              {"admin", false, false, nil},
	"GET /api/v1/model-calls":                         {"read", false, false, nil},
	"GET /api/v1/jobs":                                {"read", false, false, nil},
	"POST /api/v1/jobs/:id/cancel":                    {"write", false, false, func() interface{} { return &repository.JobModel{} }},
	"GET /api/v1/monitor/runs":                        {"read", false, false, nil},
	"GET /api/v1/evolution/runs":                      {"read", false, false, nil},
	"GET /api/v1/projects/facts/all":                  {"read", false, false, nil},
	"POST /api/v1/projects/facts":                     {"write", false, false, nil},
	"POST /api/v1/projects/facts/:id/approve":         {"review", false, false, func() interface{} { return &repository.BrandFactModel{} }},
	"POST /api/v1/harness/memory/:id/approve":         {"review", false, false, func() interface{} { return &repository.MemoryEntryModel{} }},
	"PUT /api/v1/content/assets/:id":                  {"write", false, false, func() interface{} { return &repository.ContentAssetModel{} }},
	"POST /api/v1/content/assets/:id/approve":         {"review", false, false, func() interface{} { return &repository.ContentAssetModel{} }},
	"GET /api/v1/channels":                            {"read", false, false, nil},
	"POST /api/v1/channels":                           {"admin", false, false, nil},
	"DELETE /api/v1/channels/:id":                     {"admin", false, false, func() interface{} { return &repository.PublishChannelModel{} }},
	"POST /api/v1/content/assets/:id/publish":         {"review", true, false, func() interface{} { return &repository.ContentAssetModel{} }},
	"GET /api/v1/publications":                        {"read", false, false, nil},
	"POST /api/v1/publications/:id/reconcile":         {"write", false, false, func() interface{} { return &repository.PublicationModel{} }},
	"GET /api/v1/experiments":                         {"read", false, false, nil},
	"POST /api/v1/experiments":                        {"write", false, false, nil},
	"GET /api/v1/schedules":                           {"read", false, false, nil},
	"GET /api/v1/members":                             {"read", false, false, nil},
	"PUT /api/v1/members":                             {"admin", false, false, nil},
	"GET /api/v1/projects/access":                     {"read", false, false, nil},
}

func HasProjectPolicy(method, path string) bool { _, ok := projectPolicies[method+" "+path]; return ok }
