import {useState} from 'react';import {api,streamSSE} from '../../services/api';import type {CopilotActionPreview} from '../../types';import {Page,ResourceState,useResource,useAction} from '../../components/ui/Resource';
export function PublishView({onShowToast}:{onShowToast:(title:string,note?:string)=>void}){const channels=useResource(api.getChannels);const publications=useResource(api.getPublications,5000);const assets=useResource(api.getContentAssets);const action=useAction(onShowToast);const [name,setName]=useState('');const [endpoint,setEndpoint]=useState('');const [credential,setCredential]=useState('');const [asset,setAsset]=useState('');const [channel,setChannel]=useState('');const [pending,setPending]=useState<{session_id:string;preview:CopilotActionPreview}|null>(null);
 const approve=async()=>{if(!pending)return;await streamSSE('/copilot/resume',{session_id:pending.session_id,interrupt_id:pending.preview.interrupt_id,action:'confirm'},{onError:e=>{throw e}});setPending(null)};
 return <Page title="发布管理" description="接收端必须支持幂等键和回执查询。发布只有取得真实回执后才成功；结果不确定时核对回执，避免重复发布。">
 <form className="card panel grid gap-3" onSubmit={e=>{e.preventDefault();void action.run(async()=>{await api.createChannel({name,endpoint_url:endpoint,credential});setCredential('')},'Webhook 渠道已保存')}}><h2>添加发布渠道</h2><label>名称<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>HTTPS 接收地址<input required type="url" value={endpoint} onChange={e=>setEndpoint(e.target.value)}/></label><label>访问凭证<input type="password" autoComplete="new-password" value={credential} onChange={e=>setCredential(e.target.value)}/></label><button className="btn" disabled={action.busy}>保存渠道</button></form>
 <ResourceState resource={channels} empty={!channels.data?.items.length}/>{channels.data?.items.map(c=><p key={c.id}>{c.name} · {c.is_active?'启用':'停用'} · {c.has_credential?'已配置凭证':'未配置凭证'} {c.is_active&&<button className="btn small" disabled={action.busy} onClick={()=>void action.run(()=>api.disableChannel(c.id),'渠道已停用')}>停用</button>}</p>)}
 <form className="card panel grid gap-3" onSubmit={e=>{e.preventDefault();void action.run(async()=>{setPending(await api.previewPublication(asset,channel))},'审批预览已生成')}}><h2>创建发布审批</h2><label>已批准内容<select required value={asset} onChange={e=>setAsset(e.target.value)}><option value="">选择内容</option>{assets.data?.items.filter(a=>a.status==='approved').map(a=><option key={a.id} value={a.id}>{a.title} · v{a.version}</option>)}</select></label><label>渠道<select required value={channel} onChange={e=>setChannel(e.target.value)}><option value="">选择启用渠道</option>{channels.data?.items.filter(c=>c.is_active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="btn" disabled={action.busy||!!pending}>生成预览</button></form>
 {pending&&<article className="card panel"><h2>{pending.preview.title}</h2><pre className="whitespace-pre-wrap">{JSON.stringify(pending.preview.details,null,2)}</pre><button className="btn primary" disabled={action.busy} onClick={()=>void action.run(approve,'发布任务已受理，请等待回执')}>批准并投递</button><button className="btn" disabled={action.busy} onClick={()=>void action.run(async()=>{await streamSSE('/copilot/resume',{session_id:pending.session_id,interrupt_id:pending.preview.interrupt_id,action:'cancel'},{onError:e=>{throw e}});setPending(null)},'审批已取消')}>取消</button></article>}
 <h2>发布回执</h2><ResourceState resource={publications} empty={!publications.data?.items.length}/>{publications.data?.items.map(p=><article className="card panel" key={p.id}><p>{p.id} · 内容 v{p.asset_version} · {p.status}</p><p>{p.target_url||p.error_message||'等待回执'}</p>{['publishing','outcome_unknown'].includes(p.status)&&<button className="btn" disabled={action.busy} onClick={()=>void action.run(()=>api.reconcilePublication(p.id),'回执已核对')}>核对真实回执</button>}</article>)}
 </Page>}
